name: Download data

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'
jobs:
  salem:
    runs-on: ubuntu-latest
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/New_York
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions-rs/install@v0.1
      with:
        crate: xsv
        version: latest
        use-tool-cache: true
    - name: Install npm deps
      run: npm install
    - name: Download
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 360
        max_attempts: 3
        command: node scrapers/index.js salem
      env:
        PARCEL_API: ${{ secrets.PARCEL_API }}
        PARCEL_API_TOKEN: ${{ secrets.PARCEL_API_TOKEN }}
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'data/salem'
        DEST_DIR: 'salem'
